config/routes.rb
Rails.application.routes.draw do
  resources :problems
  devise_for :authors
  # get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'readers/home#index'
  get '/blog/:id' => 'readers/posts#show', as: :blog_post

  scope module: 'authors' do
    get 'stats' => 'stats#index'
    resources :posts do
      resources :elements
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/models/element.rb
class Element < ApplicationRecord
  belongs_to :post

  validates :element_type, inclusion: { in: %w[paragraph image video-embed] }
  has_rich_text :content
  has_one_attached :image

  def paragraph?
    element_type == 'paragraph'
  end

  def image?
    element_type == 'image'
  end
end

app/models/page_view.rb
class PageView < Impression
  scope :for_type, lambda { |type|
    where(impressionable_type: type)
  }

  scope :for_date_range, lambda { |start_date, end_date|
    where(created_at: start_date.beginning_of_day..end_date.end_of_day)
  }

  def self.count_by_date(start_date, end_date)
    results = for_date_range(start_date, end_date)
              .group('date(created_at)').count

    with_zeros(start_date, end_date, results)
  end

  def self.uniq_count_by_date(start_date, end_date)
    results = for_date_range(start_date, end_date)
              .select(:ip_address)
              .distinct
              .group('date(created_at)').count

    with_zeros(start_date, end_date, results)
  end

  def self.with_zeros(start_date, end_date, results_hash)
    date_range = (start_date.to_date..end_date.to_date).to_a.map do |date|
      date.strftime('%Y-%m-%d')
    end
    results_hash.stringify_keys!
    hash_with_zeros = {}
    date_range.each do |date|
      hash_with_zeros[date] = results_hash[date] || 0
    end
    hash_with_zeros
  end
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: %i[slugged history finders]

  is_impressionable

  belongs_to :author
  has_many :elements

  has_one_attached :header_image

  validates :title, :description, presence: true
  validates :description, length: { within: 50..250 }

  scope :published, lambda {
    where(published: true)
  }

  scope :most_recently_published, lambda {
    order(published_at: :desc)
  }

  def should_generate_new_friendly_id?
    title_changed?
  end
end

app/models/post_element.rb
class PostElement < ApplicationRecord
  belongs_to :post

  validates :element_type, inclusion: {in: ['paragraph', 'image', 'video-embed']}
  has_rich_text :content
  has_one_attached :image

  def paragraph?
    element_type == 'paragraph'
  end

  def image?
    element_type == 'image'
  end
end

app/models/problem.rb
class Problem < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_action_cable_identifier

  private

  def set_action_cable_identifier
    cookies.encrypted[:author_id] = current_author&.id
  end
end

app/controllers/authors/elements_controller.rb
module Authors
  class ElementsController < AuthorsController
    before_action :set_post
    before_action :set_element, only: %i[update destroy]

    # POST /elements
    def create
      @element = @post.elements.build(element_params)

      notice = @element.save ? @element.errors.full_messages.join('. ') : nil
      redirect_to edit_post_path(@post), notice: notice
    end

    # PATCH/PUT /elements/1
    def update
      @element.update(element_params)
      redirect_to edit_post_path(@element.post) if @element.element_type != 'paragraph'
    end

    # DELETE /elements/1
    def destroy
      @element.destroy
      redirect_to edit_post_path(@element.post), notice: 'Element was successfully destroyed.'
    end

    private

    def set_post
      @post = current_author.posts.find(params[:post_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_element
      @element = @post.elements.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def element_params
      params.require(:element).permit(:element_type, :content, :image)
    end
  end
end

app/controllers/authors/posts_controller.rb
module Authors
  class PostsController < AuthorsController
    before_action :set_post, only: %i[edit update destroy]

    # GET /posts
    def index
      @posts = current_author.posts
    end

    # GET /posts/new
    def new
      @post = current_author.posts.build
    end

    # GET /posts/1/edit
    def edit
      @element = @post.elements.build
    end

    # POST /posts
    def create
      @post = current_author.posts.build(post_params)

      if @post.save
        redirect_to edit_post_path(@post)
      else
        broadcast_errors @post, post_params
      end
    end

    # PATCH/PUT /posts/1
    def update
      if @post.update(post_params)
        redirect_to edit_post_path(@post)
      else
        broadcast_errors @post, post_params
      end
    end

    # DELETE /posts/1
    def destroy
      @post.destroy
      redirect_to posts_url, notice: 'Post was successfully destroyed.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = current_author.posts.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :description, :header_image)
    end
  end
end

app/controllers/authors/stats_controller.rb
module Authors
  class StatsController < AuthorsController
    def index
      @count_by_date = PageView.count_by_date(7.days.ago, Date.today).stringify_keys
      @unique_count_by_date = PageView.uniq_count_by_date(7.days.ago, Date.today).stringify_keys
    end
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_author!

  layout 'authors'
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :set_problem, only: [:show, :edit, :update, :destroy]

  # GET /problems
  def index
    @problems = Problem.all
  end

  # GET /problems/1
  def show
  end

  # GET /problems/new
  def new
    @problem = Problem.new
  end

  # GET /problems/1/edit
  def edit
  end

  # POST /problems
  def create
    @problem = Problem.new(problem_params)

    if @problem.save
      redirect_to @problem, notice: 'Problem was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /problems/1
  def update
    if @problem.update(problem_params)
      redirect_to @problem, notice: 'Problem was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /problems/1
  def destroy
    @problem.destroy
    redirect_to problems_url, notice: 'Problem was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problem
      @problem = Problem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def problem_params
      params.require(:problem).permit(:title, :source, :code)
    end
end

app/controllers/readers/home_controller.rb
module Readers
  class HomeController < ReadersController
    def index
      @posts = Post.published.most_recently_published
    end
  end
end

app/controllers/readers/posts_controller.rb
module Readers
  # Public Blog Posts Controller
  class PostsController < ReadersController
    def show
      @post = Post.published.friendly.find(params[:id])
      impressionist(@post)
    end
  end
end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController
  layout 'readers'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/authors/elements/update.js.erb
var element = document.getElementById("element-<%= @element.id %>-form")

element.classList.add('d-none')
element.previousElementSibling.classList.remove('d-none')

var html = "<div class='trix-content'><%= @element.content.body.html_safe %></div>"
element.previousElementSibling.innerHTML = html

app/views/authors/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
    <%= form.error_for :title, class: "text-danger" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
    <%= form.error_for :description, class: "text-danger" %>
  </div>

  <div class="form-group">
    <%= form.label :header_image %>
    <%= form.file_field :header_image %>
    <div class="mt-1">
      <% if post.header_image.present? %>
        <small>Current Image:</small>
        <%= image_tag(post.header_image, width: '100%') %>
      <% end %>
    </div>
  </div>


  <div class="actions">
    <%= form.submit class: 'btn btn-primary btn-block' %>
  </div>
<% end %>

app/views/authors/posts/edit.html.erb
<div class="row">
  <div class="col-md-4">
    <%= link_to 'Back', posts_path, class: "btn btn-dark mb-3" %>
    <div class="card">
      <div class="card-header">
        <h6 class="card-title mb-0">Editing Post</h6>
      </div>
      <div class="card-body">
        <%= render 'form', post: @post %>
      </div>
      <div class="card-footer">
        <% if @post.published? %>
          <a href="#"
             class="btn btn-secondary btn-block"
             data-reflex='click->PublisherReflex#unpublish'
             data-post-id="<%= @post.id %>" >
             Unpublish
          </a>
        <% else %>
          <a href="#"
             class="btn btn-dark btn-block"
             data-reflex='click->PublisherReflex#publish'
             data-post-id="<%= @post.id %>" >
             Publish
          </a>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="mb-3">
      <%= form_with(model: [@post, @element], html: { class: 'float-left mr-1'}) do |form| %>
        <%= form.hidden_field :element_type, value: 'paragraph' %>
        <%= button_tag(type: 'submit', class: 'btn btn-secondary') do %>
          <i class="fas fa-paragraph"></i>
        <% end %>
      <% end %>
      <%= form_with(model: [@post, @element]) do |form| %>
        <%= form.hidden_field :element_type, value: 'image' %>
        <%= button_tag(type: 'submit', class: 'btn btn-secondary') do %>
          <i class="fas fa-image"></i>
        <% end %>
      <% end %>
    </div>
    <div class="card mb-5">
      <div class="card-header text-right">
        <% if @post.published? %>
          <b>Published</b> <%= time_ago_in_words(@post.published_at) %> ago
        <% else %>
          Unpublished
        <% end %>
      </div>

      <div class="card-body pt-5" data-controller="elements">
        <% if @post.elements.none? { |element| element.persisted? } %>
          <div class="p-4 text-center">
            <h2 class="text-secondary">
              <i class="fas fa-lightbulb"></i>
            </h2>
            <p>Click the icons above to add elements to this post.</p>
          </div>
        <% else %>
          <ul id='elements' data-action="drop->elements#sort">
            <% @post.elements.order(position: :asc).each do |element| %>
              <% if element.persisted? %>
                <li data-id="<%= element.id %>" class="element-item">
                  <% if element.paragraph? %>
                    <div class="mb-4 p-3 paragraph">
                      <div class="paragraph-content">
                        <% if element.content.present? %>
                          <%= element.content %>
                        <% else %>
                          Click to add content.
                        <% end %>
                      </div>
                      <div class="paragraph-form d-none" id="element-<%= element.id %>-form">
                        <%= form_with(model: [@post, element]) do |form| %>
                          <%= form.rich_text_area :content, id: "element_content_#{element.id}" %>
                          <div class="mt-3 d-flex justify-content-between">
                            <div>
                              <%= form.submit "Save", class: 'btn btn-primary' %>
                              <a href="#" class="cancel btn btn-secondary">Cancel</a>
                            </div>
                            <%= link_to 'Delete', post_element_path(@post, element), method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure?"} %>
                          </div>
                        <% end %>
                      </div>
                    </div>
                  <% elsif element.image? %>
                    <div class="mb-4 p-3 image">
                      <% if element.image.present? %>
                        <%= image_tag(element.image) %>
                        <%= link_to post_element_path(@post, element), method: :delete, class: 'delete-btn btn btn-danger mt-2 float-right', data: { confirm: "Are you sure?"} do %>
                          <i class="fas fa-times"></i>
                        <% end %>
                      <% else %>
                        <%= form_with(model: [@post, element]) do |form| %>
                          <%= form.file_field :image %>
                          <div class="mt-3">
                            <%= form.submit "Save", class: 'btn btn-primary' %>
                            <a href="#" class="cancel btn btn-secondary">Cancel</a>
                          </div>
                        <% end %>
                      <% end %>
                    </div>
                  <% end %>
                </li>
              <% end %>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/authors/posts/index.html.erb
<h4 class='d-flex justify-content-between mb-4'>
  <span>Posts</span>
  <%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>
</h4>

<% @posts.each do |post| %>
    <div class="card mb-3 post-card">
      <%= link_to(edit_post_path(post), class: 'text-decoration-none') do %>
        <div class="card-body">
          <div class="row">
            <div class="col-md-2">
              <% if post.header_image.present? %>
                <div class="header-img" style="background-image: url(<%= url_for post.header_image %>)"></div>
              <% end %>
            </div>
            <div class="col-md-10">
              <% if post.published? %>
                <span class="badge badge-primary mb-2">Published</span>
              <% else %>
                <span class="badge badge-secondary mb-2">Unpublished</span>
              <% end %>
              <h5 class="card-title mb-2 text-dark"><%= post.title %></h5>
              <p class="text-secondary mb-0"><%= post.description.truncate(200) %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
<% end %>

app/views/authors/posts/new.html.erb
<div class="row">
  <div class="col-md-4">
    <%= link_to 'Back', posts_path, class: 'btn btn-dark mb-3' %>

    <div class="card">
      <div class="card-header">
        <h6 class="card-title mb-0">New Post</h6>
      </div>
      <div class="card-body">
        <%= render 'form', post: @post %>
      </div>
    </div>
  </div>
</div>

app/views/authors/stats/index.html.erb
<h4><span>Stats</span></h4>
<div class="row">
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        7 Day Views
      </div>
      <div class="card-body">
        <canvas id="page-views" width="400" height="400" data-labels="<%= @count_by_date.keys %>" data-data="<%= @count_by_date.values %>"></canvas>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="card">
      <div class="card-header">
        7 Day Unique Views
      </div>
      <div class="card-body">
        <canvas id="unique-page-views" width="400" height="400" data-labels="<%= @unique_count_by_date.keys %>" data-data="<%= @unique_count_by_date.values %>"></canvas>
      </div>
    </div>
  </div>
</div>

app/views/problems/_form.html.erb
<%= form_with(model: problem) do |form| %>
  <% if problem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(problem.errors.count, "error") %> prohibited this problem from being saved:</h2>

      <ul>
        <% problem.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :source %>
    <%= form.text_field :source %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_area :code %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/problems/edit.html.erb
<h1>Editing Problem</h1>

<%= render 'form', problem: @problem %>

<%= link_to 'Show', @problem %> |
<%= link_to 'Back', problems_path %>

app/views/problems/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Problems</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Source</th>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @problems.each do |problem| %>
      <tr>
        <td><%= problem.title %></td>
        <td><%= problem.source %></td>
        <td><%= problem.code %></td>
        <td><%= link_to 'Show', problem %></td>
        <td><%= link_to 'Edit', edit_problem_path(problem) %></td>
        <td><%= link_to 'Destroy', problem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Problem', new_problem_path %>

app/views/problems/new.html.erb
<h1>New Problem</h1>

<%= render 'form', problem: @problem %>

<%= link_to 'Back', problems_path %>

app/views/problems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @problem.title %>
</p>

<p>
  <strong>Source:</strong>
  <%= @problem.source %>
</p>

<p>
  <strong>Code:</strong>
  <%= @problem.code %>
</p>

<%= link_to 'Edit', edit_problem_path(@problem) %> |
<%= link_to 'Back', problems_path %>

app/views/readers/home/index.html.erb
<div class="row">
  <% @posts.each do |post| %>
    <div class="col-md-6 col-lg-4">
      <div class="card post-card">
        <%= link_to(blog_post_path(post), class: 'text-decoration-none') do %>
          <div class="header-image" style="background-image: url(<%= url_for post.header_image %>)"></div>
          <% if post.header_image.present? %>
          <% end %>
          <div class="card-body d-flex flex-column">
            <h5 class="card-title"><%= post.title %></h5>
            <p class="card-text"><%= truncate(post.description, length: 250) %></p>
            <%= link_to 'Read Post', blog_post_path(post), class: 'btn btn-light mt-auto' %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/readers/posts/show.html.erb
<div class="row">
  <div class="col-lg-10 offset-lg-1">
    <%= link_to 'Back', :root, class: "btn btn-dark mb-3" %>
    <div class="card post-card mb-5">
      <div class="header-image" style="background-image: url(<%= url_for @post.header_image %>)"></div>
      <div class="card-body">
        <div class="pl-5 pr-5 pt-4 pb-4">
          <h1 class="card-title mb-5"><%= @post.title %></h1>
          <% @post.elements.each do  |element| %>
            <% if element.image? %>
              <div class="image-element mb-5">
                <%= image_tag(element.image) %>
              </div>
            <% else %>
              <div class="content-element mb-5">
                <%= element.content %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>